export const GAME_QUESTIONS: Record<string, string[]> = {
  "thisorthat": [
    "Beach date or mountain date?",
    "Late-night calls or morning texts?",
    "Hugs or forehead kisses?",
    "Movies at home or theatre dates?",
    "Pizza or burgers?",
    "Rainy days or winter nights?",
    "Cute selfies or candid photos?",
    "Coffee or tea?",
    "Long drives or long walks?",
    "Matching outfits or matching wallpapers?",
    "Sunrise or sunset?",
    "Sweet messages or surprise gifts?",
    "Voice calls or video calls?",
    "Stay in or go out?",
    "Ice cream or chocolate?",
    "Funny partner or romantic partner?",
    "Instagram reels or YouTube videos?",
    "Singing together or dancing together?",
    "Cats or dogs?",
    "Texting all day or one deep conversation?",
    "Watching stars or watching the sea?",
    "Road trip or flight trip?",
    "Pancakes or waffles?",
    "Hoodie stealing or pillow stealing?",
    "Handwritten letters or long paragraphs?",
    "Adventure date or cozy date?",
    "Fast replies or thoughtful replies?",
    "Flowers or chocolates?",
    "Phone calls while sleeping or goodnight texts?",
    "Fancy dinner or street food date?",
    "Gold jewelry or silver jewelry?",
    "Comedy movies or horror movies?",
    "Being the clingy one or being chased?",
    "Summer or monsoon?",
    "Surprise plans or planned dates?",
    "Deep talks or playful teasing?",
    "Watching series together or gaming together?",
    "Morning cuddles or night cuddles?",
    "City life or village life?",
    "Tattoos or piercings?",
    "Snapchat streaks or Spotify playlists?",
    "Window seat or aisle seat?",
    "Sleeping early or staying up late?",
    "Sweet spicy food or extra spicy food?",
    "Holding hands or arm around shoulder?",
    "Mini dates or grand dates?",
    "Flirty chats or emotional talks?",
    "Shopping together or cooking together?",
    "Rain walk or bike ride?",
    "Roses or sunflowers?",
    "Watching memes together or sending memes separately?",
    "Call first or text first?",
    "Anime or K-dramas?",
    "Birthday surprises or anniversary surprises?",
    "Matching rings or matching bracelets?",
    "Big wedding or private wedding?",
    "Singing in car or silent ride?",
    "Romantic songs or sad songs?",
    "Cake or ice cream for celebrations?",
    "Photo albums or video memories?",
    "Going viral online or staying private?",
    "Long hair or short hair?",
    "Gentle teasing or savage roasting?",
    "Watching cricket or football?",
    "Public affection or private affection?",
    "Fancy cafes or roadside tea shops?",
    "Cute nicknames or real names?",
    "Good morning texts or random “I miss you” texts?",
    "Theme parks or beaches?",
    "Sharing food or ordering separately?",
    "Staying friends first or instant romance?",
    "Taking photos or being in photos?",
    "Matching phone cases or matching hoodies?",
    "Singing badly together or dancing badly together?",
    "Rich and busy or simple and peaceful?",
    "Phone wallpaper of partner or hidden lockscreen?",
    "Winter cuddles or rainy cuddles?",
    "Big surprises or little daily efforts?",
    "TikTok trends or original ideas?",
    "Loud love or silent love?",
    "Couple tattoos or promise rings?",
    "Talking nonstop or comfortable silence?",
    "Fancy gifts or handmade gifts?",
    "Chocolate milkshake or strawberry milkshake?",
    "Roller coaster or Ferris wheel?",
    "Watching old chats or old photos?",
    "Protective partner or chill partner?",
    "Cute aggression or soft affection?",
    "Rewatching favorite movie or trying new movie?",
    "Casual dates or dressed-up dates?",
    "Being spoiled or spoiling partner?",
    "Snow trip or island trip?",
    "Study dates or gaming dates?",
    "Big spoon or little spoon?",
    "Couple playlists or couple journals?",
    "Long hugs or quick kisses?",
    "Love at first sight or slow-burn love?",
    "Matching bios or matching usernames?",
    "Quiet romance or chaotic romance?",
    "Forever texting or forever calling?"
  ],
  "answerreveal": [
    "What was your first impression of me?",
    "When did you realize you liked me?",
    "What is your favorite memory with me?",
    "What is one thing you never told me before?",
    "What song reminds you of me?",
    "What is my cutest habit?",
    "What moment made you smile the most recently?",
    "What is one thing you want us to do together?",
    "What is your favorite photo of us?",
    "What is something I do that comforts you?",
    "What is my funniest moment?",
    "What nickname would you give me?",
    "What color suits me best?",
    "What do you miss about me right now?",
    "What is your dream date with me?",
    "What food reminds you of me?",
    "Which of my messages made you happiest?",
    "What do you think I overthink the most?",
    "What makes us special?",
    "What is one thing you want to improve in our relationship?",
    "What is your favorite thing about my personality?",
    "What is one thing you admire about me?",
    "What emoji reminds you of me?",
    "What is your comfort memory of us?",
    "What is one thing you want me to know forever?",
    "What was your favorite conversation with me?",
    "What makes you feel closest to me?",
    "What is your favorite compliment from me?",
    "What is one small thing I do that matters a lot?",
    "Which movie couple are we similar to?",
    "What is your favorite thing about my voice?",
    "What is one thing you want to experience together?",
    "What is your favorite late-night memory with me?",
    "What made you trust me?",
    "What would our future house look like?",
    "What outfit of mine do you love most?",
    "What is one thing that instantly reminds you of me?",
    "What was your happiest day with me?",
    "What is your favorite inside joke?",
    "What is one thing I do that makes you blush?",
    "What is your favorite text from me?",
    "What moment made you emotional because of me?",
    "What is your favorite thing to do together?",
    "What do you think our relationship needs more of?",
    "What animal would represent us?",
    "What is your favorite way I show love?",
    "What would our dream vacation be?",
    "What is your favorite thing about our chats?",
    "What is one thing we should try together?",
    "What would our couple aesthetic be?",
    "What makes our bond different?",
    "What was your most unforgettable moment with me?",
    "What is one word that describes me perfectly?",
    "What is one thing you hope never changes about us?",
    "What reminds you of our first conversation?",
    "What is your favorite random memory of us?",
    "What do you think I secretly love?",
    "What is your favorite thing about my eyes?",
    "What moment made you laugh hardest?",
    "What future memory are you excited for?",
    "What would you do if we met right now?",
    "What is your favorite sleepy conversation memory?",
    "What is one thing I should hear today?",
    "What would our couple song be?",
    "What is one thing we are perfectly opposite in?",
    "What is your favorite thing I call you?",
    "What place should we visit together?",
    "What do you think makes me attractive?",
    "What is your favorite reaction of mine?",
    "What would our dream weekend look like?",
    "What is your favorite thing I wear?",
    "What do you think I deserve more of?",
    "What is something cute we should start doing?",
    "What memory do you replay often?",
    "What is your favorite “us” moment?",
    "What smell reminds you of me?",
    "What makes you feel safe with me?",
    "What should we do on our next date?",
    "What is one thing we would be great at together?",
    "What is your favorite thing about our chemistry?",
    "What was the sweetest thing I did?",
    "What is one thing you want to thank me for?",
    "What is your favorite random text from me?",
    "What scene would fit us in a movie?",
    "What is your favorite thing we discovered together?",
    "What is one thing you wish we did more often?",
    "What moment made you think “this is special”?",
    "What kind of old couple will we become?",
    "What is your favorite compliment to receive from me?",
    "What is one thing you hope we never stop doing?",
    "What color represents our relationship?",
    "What fictional world would you take me to?",
    "What is one thing I do unintentionally cute?",
    "What is your favorite voice note from me?",
    "What is one thing we should celebrate more?",
    "What do you think our love language is?",
    "What is your favorite peaceful memory with me?",
    "What is your favorite chaotic memory with me?",
    "What do you think destiny did right with us?",
    "What is your favorite thing about being with me?"
  ],
  "guessmyanswer": [
    "Guess my favorite color.",
    "Guess my favorite food.",
    "Guess my dream vacation place.",
    "Guess my favorite movie genre.",
    "Guess my biggest fear.",
    "Guess my comfort snack.",
    "Guess my favorite season?",
    "Guess my favorite app.",
    "Guess my favorite time of day.",
    "Guess my celebrity crush.",
    "Guess my favorite song.",
    "Guess my dream car.",
    "Guess my favorite animal.",
    "Guess my favorite dessert.",
    "Guess my favorite outfit style.",
    "Guess my favorite emoji.",
    "Guess my favorite memory with you.",
    "Guess my most-used word.",
    "Guess my favorite social media app.",
    "Guess my dream job.",
    "Guess what instantly annoys me.",
    "Guess what makes me happy quickly.",
    "Guess my favorite beverage.",
    "Guess my favorite type of date.",
    "Guess my biggest green flag.",
    "Guess my weirdest habit.",
    "Guess my favorite weather.",
    "Guess my favorite chocolate.",
    "Guess my favorite music vibe.",
    "Guess my favorite festival.",
    "Guess my favorite subject.",
    "Guess my favorite game.",
    "Guess what I overthink most.",
    "Guess my favorite compliment.",
    "Guess my dream pet.",
    "Guess my favorite actor.",
    "Guess my favorite flower.",
    "Guess my hidden talent.",
    "Guess my comfort movie.",
    "Guess my favorite late-night activity.",
    "Guess my favorite nickname from you.",
    "Guess my favorite thing about you.",
    "Guess my favorite holiday destination.",
    "Guess my favorite junk food.",
    "Guess what makes me blush.",
    "Guess my favorite childhood cartoon.",
    "Guess my favorite ringtone.",
    "Guess my favorite smell.",
    "Guess my favorite random memory.",
    "Guess my favorite fast food chain.",
    "Guess my favorite sport.",
    "Guess my favorite fruit.",
    "Guess my dream house style.",
    "Guess my favorite type of hug.",
    "Guess my favorite mobile game.",
    "Guess my favorite hairstyle on you.",
    "Guess my favorite café drink.",
    "Guess my favorite midnight snack.",
    "Guess my ideal weekend.",
    "Guess my favorite pickup line.",
    "Guess my favorite holiday.",
    "Guess my favorite rainy-day activity.",
    "Guess my favorite thing to hear from you.",
    "Guess my favorite road trip song.",
    "Guess my favorite app to waste time on.",
    "Guess my favorite kind of surprise.",
    "Guess my favorite pizza topping.",
    "Guess my favorite way to relax.",
    "Guess my favorite photo of us.",
    "Guess my favorite way to flirt.",
    "Guess my favorite memory from childhood.",
    "Guess my favorite style of texting.",
    "Guess my favorite thing to collect.",
    "Guess my favorite fictional character.",
    "Guess my favorite board game.",
    "Guess my favorite gift type.",
    "Guess my favorite café snack.",
    "Guess my favorite sleeping position.",
    "Guess my favorite dance move.",
    "Guess my favorite thing to do when bored.",
    "Guess my favorite type of kiss.",
    "Guess my favorite topic to talk about.",
    "Guess my favorite emoji combo.",
    "Guess my favorite kind of weather.",
    "Guess my favorite comfort place.",
    "Guess my favorite thing about calls with you.",
    "Guess my favorite thing to hear before sleep.",
    "Guess my favorite social activity.",
    "Guess my favorite random purchase.",
    "Guess my favorite memory this year.",
    "Guess my favorite aesthetic.",
    "Guess my favorite couple activity.",
    "Guess my favorite thing to post online.",
    "Guess my favorite kind of humor.",
    "Guess my favorite adventure idea.",
    "Guess my favorite thing to receive unexpectedly.",
    "Guess my favorite thing we do together.",
    "Guess my favorite comfort phrase.",
    "Guess my favorite thing about relationships.",
    "Guess my favorite dream for us."
  ],
  "completesentence": [
    "I feel happiest when...",
    "My favorite thing about you is...",
    "I wish we could...",
    "The cutest thing you do is...",
    "I knew I liked you when...",
    "My dream date would be...",
    "One thing I never get tired of is...",
    "You always make me smile when...",
    "Our relationship feels like...",
    "I secretly love when you...",
    "One memory I replay often is...",
    "I feel safe when...",
    "One thing I want to tell you more is...",
    "If we traveled together, I would want to...",
    "You look cutest when...",
    "One thing I admire about you is...",
    "I miss you the most when...",
    "My favorite conversation with you was...",
    "I laugh hardest when...",
    "One thing we should do together is...",
    "I feel lucky because...",
    "Your voice sounds best when...",
    "I think our biggest strength is...",
    "I would love to surprise you with...",
    "One thing I notice about you is...",
    "Our future should include...",
    "My favorite thing about your personality is...",
    "I smile every time you...",
    "I never expected us to...",
    "One thing that comforts me is...",
    "I love hearing you...",
    "I feel connected to you when...",
    "One thing I want us to improve is...",
    "The funniest thing about us is...",
    "My ideal lazy day with you is...",
    "One thing I appreciate deeply is...",
    "I love your reaction when...",
    "Our cutest habit is...",
    "I would pause time when...",
    "One thing that reminds me of you is...",
    "I feel proud of us because...",
    "One thing I always want from us is...",
    "You make ordinary moments feel...",
    "My favorite “us” vibe is...",
    "One thing I learned from you is...",
    "I feel butterflies when...",
    "The sweetest thing you did was...",
    "I love staying awake with you because...",
    "One thing I hope never changes is...",
    "I would choose you because...",
    "One random thing I adore is...",
    "You make me feel...",
    "One thing we should celebrate more is...",
    "I trust you because...",
    "One thing I dream about is...",
    "I love your smile when...",
    "My favorite memory recently was...",
    "One thing we are really good at is...",
    "I would love to watch...",
    "You understand me when...",
    "One thing that melts my heart is...",
    "I feel excited when...",
    "Our best conversations happen when...",
    "One thing I want to experience together is...",
    "I think we are perfect at...",
    "One thing I secretly want is...",
    "I feel calm when...",
    "One thing you should know is...",
    "I love how we...",
    "One thing that always cheers me up is...",
    "You make love feel...",
    "One thing I want to thank you for is...",
    "My favorite thing about our calls is...",
    "I think our future self would...",
    "One thing I would relive is...",
    "You always surprise me when...",
    "I feel understood when...",
    "One thing I can’t resist is...",
    "I would spend all day...",
    "One thing that defines us is...",
    "I think your cutest feature is...",
    "I would love a date where...",
    "One thing that makes us unique is...",
    "I feel emotional when...",
    "Our relationship deserves...",
    "One thing I would never forget is...",
    "I want more moments where...",
    "One thing that instantly reminds me of you is...",
    "I think our bond feels like...",
    "I appreciate you because...",
    "One thing I wish for us is...",
    "I love the way you...",
    "My favorite comfort moment is...",
    "One thing we should try soon is...",
    "I feel happiest hearing...",
    "You make difficult days...",
    "One thing I hope we always do is...",
    "I love us because...",
    "One thing I’ll always remember is...",
    "Forever with you would feel like..."
  ],
  "dailyquestion": [
    "What made you smile today?",
    "What was the best part of your day?",
    "What are you thinking about right now?",
    "What is one thing you are grateful for today?",
    "What song matched your mood today?",
    "What made you laugh today?",
    "What drained your energy today?",
    "What gave you peace today?",
    "What do you want right now?",
    "What did you miss today?",
    "What are you excited for?",
    "What is your comfort food today?",
    "What color describes your mood today?",
    "What was your most random thought today?",
    "What memory crossed your mind today?",
    "What do you need more of lately?",
    "What are you proud of today?",
    "What annoyed you today?",
    "What did you learn today?",
    "What would make today better?",
    "What is one thing you want to improve?",
    "What made you emotional today?",
    "What made you feel loved today?",
    "What made you overthink today?",
    "What did you enjoy most today?",
    "What are you craving today?",
    "What was your favorite conversation today?",
    "What gave you comfort today?",
    "What are you avoiding lately?",
    "What inspired you today?",
    "What made you tired today?",
    "What made your day easier?",
    "What are you thankful for in us?",
    "What was your favorite moment today?",
    "What made you happiest today?",
    "What are you looking forward to tomorrow?",
    "What kind of vibe did today have?",
    "What is one thing you need to hear today?",
    "What is your current obsession?",
    "What are you curious about lately?",
    "What made you feel calm today?",
    "What distracted you most today?",
    "What did you wish happened today?",
    "What gave you motivation today?",
    "What made you smile unexpectedly?",
    "What was your comfort activity today?",
    "What are you dreaming about lately?",
    "What made you feel confident today?",
    "What are you grateful for about yourself?",
    "What is one thing you want from tomorrow?",
    "What made you feel appreciated today?",
    "What did you enjoy watching today?",
    "What was your favorite meal today?",
    "What made you think of me today?",
    "What is your energy level today?",
    "What made you feel safe today?",
    "What would improve your mood right now?",
    "What was your biggest win today?",
    "What are you missing lately?",
    "What is your current comfort song?",
    "What did you overthink today?",
    "What made you laugh hardest today?",
    "What are you excited to tell me?",
    "What gave you butterflies today?",
    "What was your favorite small moment?",
    "What made you relax today?",
    "What do you wish we could do today?",
    "What is one thing you appreciate about life today?",
    "What challenged you today?",
    "What are you hoping for this week?",
    "What did you spend too much time on today?",
    "What made today memorable?",
    "What would you rate today out of 10?",
    "What made you feel understood today?",
    "What made you smile thinking about us?",
    "What was the funniest thing today?",
    "What made your heart feel full today?",
    "What are you currently stressed about?",
    "What was your comfort moment today?",
    "What did you enjoy doing alone today?",
    "What made you feel productive today?",
    "What would make this week amazing?",
    "What made you feel connected today?",
    "What is your current favorite routine?",
    "What do you want more of from life?",
    "What gave you energy today?",
    "What was your favorite text today?",
    "What made you feel emotional?",
    "What kind of weather matched your mood today?",
    "What did you enjoy listening to today?",
    "What was your biggest thought today?",
    "What made you feel cozy today?",
    "What was your favorite surprise today?",
    "What are you currently thankful for in us?",
    "What was today missing?",
    "What did you do best today?",
    "What would make tomorrow perfect?",
    "What is your current comfort place?",
    "What is something you want to remember about today?",
    "What would you tell your future self about today?"
  ],
  "truthordare": [
    "Truth: What was your first thought about me?",
    "Dare: Send your cutest selfie.",
    "Truth: What is your biggest green flag?",
    "Dare: Describe me in 3 dramatic words.",
    "Truth: What makes you jealous?",
    "Dare: Change my contact name for 1 day.",
    "Truth: What is your favorite thing about me?",
    "Dare: Send a random voice note.",
    "Truth: What is your weirdest habit?",
    "Dare: Sing one line of a song.",
    "Truth: What moment made you blush recently?",
    "Dare: Tell me your last searched thing.",
    "Truth: What is your biggest fear in relationships?",
    "Dare: Text me only in emojis for 5 minutes.",
    "Truth: What outfit of mine do you like most?",
    "Dare: Send your funniest photo.",
    "Truth: Have you stalked me before?",
    "Dare: Say something cheesy.",
    "Truth: What do you secretly love?",
    "Dare: Tell me your current mood dramatically.",
    "Truth: What is your favorite memory of us?",
    "Dare: Write a fake movie title about us.",
    "Truth: What instantly makes you smile?",
    "Dare: Reveal your screen time.",
    "Truth: What is your comfort song?",
    "Dare: Send a random old picture.",
    "Truth: What do you overthink the most?",
    "Dare: Speak in a fake accent for 1 minute.",
    "Truth: What is one thing you miss?",
    "Dare: Tell me a pickup line.",
    "Truth: What was your most embarrassing moment?",
    "Dare: Send your most-used emoji.",
    "Truth: What is your dream date?",
    "Dare: Tell me your funniest secret.",
    "Truth: What makes you emotional?",
    "Dare: Rate my flirting skills.",
    "Truth: What do you admire about me?",
    "Dare: Send a random paragraph.",
    "Truth: What is your biggest ick?",
    "Dare: Recreate your favorite selfie pose.",
    "Truth: What is your favorite late-night memory?",
    "Dare: Say one thing you never said before.",
    "Truth: What kind of dates do you love?",
    "Dare: Send a dramatic “I miss you” message.",
    "Truth: What is your comfort activity?",
    "Dare: Make up a nickname for me.",
    "Truth: What would our future house look like?",
    "Dare: Pretend to propose dramatically.",
    "Truth: What was your first impression of me?",
    "Dare: Tell me your current craving.",
    "Truth: What do you secretly want more of?",
    "Dare: Send a song that matches us.",
    "Truth: What is your favorite compliment?",
    "Dare: Write a tiny poem.",
    "Truth: What memory do you replay often?",
    "Dare: Act like a movie villain.",
    "Truth: What is your favorite thing about calls?",
    "Dare: Talk only in questions for 2 minutes.",
    "Truth: What makes you feel loved?",
    "Dare: Describe me like a product review.",
    "Truth: What is your cutest habit?",
    "Dare: Send a random meme.",
    "Truth: What scares you about the future?",
    "Dare: Make a fake award for me.",
    "Truth: What is your comfort place?",
    "Dare: Give me a silly challenge.",
    "Truth: What is your favorite random memory?",
    "Dare: Describe our relationship as a movie genre.",
    "Truth: What do you appreciate most about us?",
    "Dare: Tell me your funniest typo.",
    "Truth: What do you want us to experience?",
    "Dare: Say something sweet dramatically.",
    "Truth: What makes you feel safe?",
    "Dare: Use only GIFs for 5 minutes.",
    "Truth: What is your favorite thing I say?",
    "Dare: Reveal your last saved photo.",
    "Truth: What is your favorite thing about yourself?",
    "Dare: Create a slogan for our relationship.",
    "Truth: What is your current obsession?",
    "Dare: Send a cute “goodnight” style message now.",
    "Truth: What would you relive forever?",
    "Dare: Tell me a fake rumor about yourself.",
    "Truth: What is your favorite comfort food?",
    "Dare: Make up a random story about us.",
    "Truth: What makes you happiest lately?",
    "Dare: Explain your mood using movie titles.",
    "Truth: What is your biggest dream?",
    "Dare: Write one sentence flirting with me.",
    "Truth: What is your favorite thing we do together?",
    "Dare: Send your oldest screenshot.",
    "Truth: What is one thing you want to improve?",
    "Dare: Tell me your dramatic love story intro.",
    "Truth: What is your favorite thing to hear?",
    "Dare: Describe your mood as weather.",
    "Truth: What makes our relationship special?",
    "Dare: Give me a random dare back.",
    "Truth: What is your comfort conversation?",
    "Dare: Send a voice note laughing.",
    "Truth: What do you hope for us?",
    "Dare: Tell me something sweet before ending the game."
  ],
  "moodsync": [
    "What emoji matches your mood right now?",
    "What color is your mood today?",
    "What song fits your mood currently?",
    "Are you feeling calm or chaotic?",
    "What weather matches your mood?",
    "What movie genre fits your energy today?",
    "What word describes your vibe today?",
    "What food matches your mood?",
    "What animal represents your current energy?",
    "What time of day feels like your mood?",
    "Are you feeling clingy or independent today?",
    "What drink matches your vibe?",
    "What aesthetic matches your mood?",
    "Are you mentally tired or physically tired?",
    "What would heal your mood right now?",
    "What song lyric matches today?",
    "What fictional character matches your energy?",
    "Are you feeling social or quiet?",
    "What smell matches your mood?",
    "What activity would improve your mood?",
    "What place feels like your current mood?",
    "What app matches your energy today?",
    "What season represents your mood?",
    "Are you feeling romantic or sleepy?",
    "What kind of hug do you need today?",
    "What kind of conversation do you want today?",
    "What emoji combo matches your vibe?",
    "What comfort item matches your mood?",
    "Are you feeling motivated or lazy?",
    "What fictional world fits your energy?",
    "What snack matches your mood?",
    "What color combo represents today?",
    "What kind of music do you need?",
    "What sounds relaxing right now?",
    "Are you feeling soft or savage today?",
    "What kind of date matches your mood?",
    "What weather would fix your mood?",
    "What social battery level are you at?",
    "What vibe does your room feel like today?",
    "What meme describes your energy?",
    "What comfort show matches your mood?",
    "What kind of text do you want to receive?",
    "What type of silence fits today?",
    "What game matches your mood?",
    "What would instantly cheer you up?",
    "What does your heart need today?",
    "What photo aesthetic matches your mood?",
    "What would your mood wear today?",
    "What flavor represents your energy?",
    "What random object describes your mood?",
    "What dream destination matches today?",
    "What kind of sky matches your vibe?",
    "What romantic gesture would fit today?",
    "What sleeping style matches your energy?",
    "What cartoon represents your mood?",
    "What kind of playlist do you need?",
    "What quote matches your mood?",
    "What phone wallpaper would fit your vibe?",
    "What kind of attention do you want?",
    "What movie scene fits today?",
    "What hobby matches your mood?",
    "What random word describes your brain today?",
    "What energy are you giving today?",
    "What would make you feel safe right now?",
    "What kind of weather is your heart today?",
    "What vibe should tonight have?",
    "What style matches your energy?",
    "What random thing sounds comforting?",
    "What social media app matches your mood?",
    "What object represents your patience today?",
    "What kind of reassurance do you need?",
    "What does your brain sound like today?",
    "What outfit vibe matches your mood?",
    "What emoji should describe today forever?",
    "What fictional couple matches us today?",
    "What dream fits your current mood?",
    "What song would play in your background today?",
    "What sounds emotionally comforting?",
    "What vibe do you want from me today?",
    "What random memory matches your mood?",
    "What kind of cuddles fit today?",
    "What internet trend matches your energy?",
    "What room aesthetic matches your vibe?",
    "What kind of peace do you need?",
    "What type of sunset matches your mood?",
    "What emotion is strongest today?",
    "What random sentence describes your mood?",
    "What vibe should tomorrow have?",
    "What comfort phrase do you need?",
    "What mood are your eyes giving today?",
    "What song genre are you today?",
    "What random craving matches your vibe?",
    "What internet meme are you emotionally?",
    "What personality mode are you in today?",
    "What energy should we have together today?",
    "What kind of love do you need today?",
    "What small thing would improve today?",
    "What kind of peace are you searching for?",
    "What emotional weather forecast fits you?",
    "What word should define today?"
  ],
  "memoryquiz": [
    "What was our first conversation about?",
    "Who texted first?",
    "What was my first impression of you?",
    "What was our first inside joke?",
    "What song reminds us of early days?",
    "What was our first late-night conversation about?",
    "What was the first nickname we used?",
    "What was our first argument about?",
    "What was the first thing we bonded over?",
    "What was the first compliment I gave you?",
    "What was the first photo we shared?",
    "What was our first favorite emoji together?",
    "What was the first thing we watched together?",
    "What was our first memorable call like?",
    "What was the first random thing we laughed about?",
    "What was our first shared obsession?",
    "What did we talk about most at first?",
    "What was our first “cute” moment?",
    "What was the first thing you noticed about me?",
    "What was the first food we talked about?",
    "What was the first playlist we shared?",
    "What was our first awkward moment?",
    "What was our first deep conversation about?",
    "What was our first funny misunderstanding?",
    "What was our first screenshot-worthy chat?",
    "What was our first movie discussion?",
    "What was our first long call duration?",
    "What was our first random memory together?",
    "What was our first “I miss you” moment?",
    "What was our first virtual date?",
    "What was our first shared favorite song?",
    "What was our first wholesome moment?",
    "What was our first dream together?",
    "What was our first emotional conversation?",
    "What was our first memorable goodnight?",
    "What was our first reaction photo?",
    "What was our first cute fight?",
    "What was our first gaming moment together?",
    "What was our first matching thing?",
    "What was our first comfort moment?",
    "What was our first romantic joke?",
    "What was our first coincidence?",
    "What was our first favorite memory?",
    "What was our first random challenge?",
    "What was our first surprise?",
    "What was our first sweet paragraph?",
    "What was our first emotional support moment?",
    "What was our first long texting streak?",
    "What was our first funny typo?",
    "What was our first sleepy conversation?",
    "What was our first chaotic moment?",
    "What was our first screenshot together?",
    "What was our first dream vacation discussion?",
    "What was our first comfort song?",
    "What was our first “couple” vibe moment?",
    "What was our first favorite memory together?",
    "What was our first random challenge?",
    "What was our first dramatic moment?",
    "What was our first matching profile thing?",
    "What was our first moment of trust?",
    "What was our first “we are similar” realization?",
    "What was our first emotional laugh?",
    "What was our first memorable morning text?",
    "What was our first virtual movie night?",
    "What was our first “this feels special” moment?",
    "What was our first random coincidence?",
    "What was our first comfort conversation?",
    "What was our first future plan discussion?",
    "What was our first favorite selfie together?",
    "What was our first unforgettable moment?",
    "What was our first jealous moment?",
    "What was our first supportive moment?",
    "What was our first relationship joke?",
    "What was our first “aww” moment?",
    "What was our first favorite chat topic?",
    "What was our first matching wallpaper idea?",
    "What was our first “good vibe” moment?",
    "What was our first emotional voice note?",
    "What was our first shared comfort thing?",
    "What was our first dream future topic?",
    "What was our first favorite memory this year?",
    "What was our first big laugh together?",
    "What was our first “we think alike” moment?",
    "What was our first playful teasing moment?",
    "What was our first wholesome interaction?",
    "What was our first “I can trust you” moment?",
    "What was our first random obsession together?",
    "What was our first shared mood song?",
    "What was our first “I miss this” memory?",
    "What was our first cozy conversation?",
    "What was our first comfort habit?",
    "What was our first funny reaction image?",
    "What was our first long emotional talk?",
    "What was our first “this is us” moment?",
    "What was our first cute compliment?",
    "What was our first favorite day together?",
    "What was our first funny misunderstanding?",
    "What was our first “I want more moments like this” feeling?",
    "What was our first memory worth replaying forever?",
    "What is your favorite memory of us overall?"
  ],
  "randomquestion": [
    "If we swapped lives for a day, what would happen?",
    "What would our movie title be?",
    "Which fictional couple are we closest to?",
    "If we opened a café together, what would it be called?",
    "What weird food combo would you make me try?",
    "If we had a pet together, what would we name it?",
    "What superpower would fit our relationship?",
    "If our chats became a book, what genre would it be?",
    "What would our dream apartment look like?",
    "What random thing would instantly remind you of me?",
    "If we could teleport anywhere now, where would we go?",
    "What kind of old couple would we become?",
    "What color would represent us?",
    "If we had a YouTube channel, what would we post?",
    "What would our couple logo look like?",
    "If our relationship had a soundtrack, what vibe would it have?",
    "What would be our funniest habit as roommates?",
    "What fictional world would you take us to?",
    "What random object represents our relationship?",
    "What challenge would we definitely fail together?",
    "If we were weather, what would we be?",
    "What game show would we dominate?",
    "What would our dream midnight plan be?",
    "What snack best represents us?",
    "What random thing would we argue about jokingly?",
    "What would our matching tattoos be?",
    "What would our dream road trip playlist include?",
    "What would our relationship smell like?",
    "What would our perfect lazy Sunday look like?",
    "If we had a secret handshake, what would it include?",
    "What random app would we create together?",
    "What kind of aesthetic matches us?",
    "What weird rule would exist in our house?",
    "What movie scene feels like us?",
    "What random adventure should we try?",
    "If we had a time machine, where would we go?",
    "What would our dream vacation disaster be?",
    "What random thing would we become famous for?",
    "What weird talent would we win awards for?",
    "What board game would cause chaos between us?",
    "What fictional pet would suit us?",
    "What random thing would we collect together?",
    "What would our dream date in rain look like?",
    "What random thing would we spend too much money on?",
    "What internet trend would we fail horribly at?",
    "What random thing would make us laugh forever?",
    "What kind of café date suits us?",
    "What would our dream bedroom vibe be?",
    "What random challenge should we do someday?",
    "What weird nickname would old people give us?",
    "What random thing would we compete over?",
    "What weird food challenge would we survive?",
    "What random memory would we replay forever?",
    "What would our dream couple photoshoot theme be?",
    "What random phrase would define us?",
    "What fictional universe would we survive in?",
    "What random thing would instantly start a laugh?",
    "What kind of playlist fits our relationship?",
    "What random business would we fail at together?",
    "What kind of weather date suits us?",
    "What random skill should we learn together?",
    "What weird tradition should we start?",
    "What random thing would make our future kids laugh?",
    "What random social media trend fits us?",
    "What random object would symbolize us forever?",
    "What kind of matching outfits would we wear?",
    "What random memory should become a movie scene?",
    "What random thing would we get addicted to together?",
    "What random challenge would make us cry laughing?",
    "What weird thing would we argue over playfully?",
    "What random thing would we buy impulsively?",
    "What random thing would instantly calm us down?",
    "What dream festival would we attend together?",
    "What weird thing would we become experts at?",
    "What random topic would we make deep?",
    "What random thing would become our inside joke?",
    "What random reality show would we win?",
    "What random thing would we decorate our house with?",
    "What random memory deserves a framed photo?",
    "What random thing would we stay awake discussing?",
    "What weird thing would we celebrate yearly?",
    "What random thing would define our friendship side?",
    "What random thing would we teach each other?",
    "What random thing would we do during power cuts?",
    "What random adventure sounds fun right now?",
    "What random thing would become “our thing”?",
    "What random place would become special to us?",
    "What weird thing would we make competitive?",
    "What random sentence sounds like us?",
    "What random object would tell our story?",
    "What weird thing would we put in our dream house?",
    "What random thing would make us emotional?",
    "What random plan would become unforgettable?",
    "What random thing would we never stop teasing about?",
    "What weird thing would we enjoy doing together?",
    "What random thing would become our comfort habit?",
    "What random place would we revisit forever?",
    "What weird thing would we absolutely fail together?",
    "What random dream should we make real?",
    "What random thing makes you think “this is us”?"
  ]
};

export function getRandomQuestion(type: string): { question: string; options?: string[]; type?: "truth" | "dare" } {
  const list = GAME_QUESTIONS[type];
  if (!list || list.length === 0) return { question: "Error loading questions" };
  const q = list[Math.floor(Math.random() * list.length)];

  if (type === "thisorthat") {
    const parts = q.replace("?", "").split(" or ");
    return {
      question: q,
      options: parts.map((p) => p.trim()),
    };
  }

  if (type === "truthordare") {
    if (q.startsWith("Truth: ")) return { question: q.substring(7), type: "truth" };
    if (q.startsWith("Dare: ")) return { question: q.substring(6), type: "dare" };
  }

  return { question: q };
}